#!/bin/sh
#
# @name FlightAxis Quadrotor
#
# @type Quadrotor x
#

. ${R}etc/init.d/rc.mc_defaults

# RealFlight free-runs (no lockstep), GPS samples arrive fresh
# Forced with "param set": px4-rc.mavlinksim runs after this file and would
# otherwise override the default back to 10 ms.
param set EKF2_GPS_DELAY 0

# Actuator geometry (QGC Actuators tab) MUST match the "px4" output indices
# in Tools/simulation/flightaxis/flightaxis_bridge/models/quad.json.
#
# PWM_MAIN_FUNC<N> lands on HIL_ACTUATOR_CONTROLS.controls[N-1], so the
# assignments below produce:
#
#   controls[0] = 101 Motor 1     [0,1] -> quad.json rf0
#   controls[1] = 102 Motor 2     [0,1] -> quad.json rf1
#   controls[2] = 103 Motor 3     [0,1] -> quad.json rf2
#   controls[3] = 104 Motor 4     [0,1] -> quad.json rf3
param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.15
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.15
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.15
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.15
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
